services:
  ssb:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    environment:
      DJANGO_PORT: 8080
      DJANGO_HOST: ssb
      ENVIRONMENT: development
      CORS_ALLOWED_ORIGINS: http://astrotech-spaceapp.space,https://astrotech-spaceapp.space,http://ssf:5173,http://localhost:5173,http://ssb:8080
      PROJECT_DIR: /app
      DJANGO_SECRET_KEY: python3manage.pyrunserver
    ports:
      - "8080:8080"
    networks:
      - solary-system

  ssf:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client
    ports:
      - "5173:5173"
    networks:
      - solary-system

networks:
  solary-system:
    driver: bridge

# services:
#   ssb:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     volumes:
#       - ./server:/app/server
#     environment:
#       DJANGO_PORT: 8080
#       DJANGO_HOST: ssb
#       ENVIRONMENT: development
#       CORS_ALLOWED_ORIGINS: http://astrotech-spaceapp.space
#       PROJECT_DIR: /app
#       DJANGO_SECRET_KEY: your-secret-key
#     ports:
#       - "8080:8080"
#     networks:
#       - solary-system

#   ssf:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     volumes:
#       - ./client:/app/client
#     ports:
#       - "5173:5173"
#     networks:
#       - solary-system

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - ./client:/usr/share/nginx/html
#     depends_on:
#       - ssb
#     networks:
#       - solary-system

# networks:
#   solary-system:
#     driver: bridge